/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as crossChainNameServiceReceiverSol from "./CrossChainNameServiceReceiver.sol";
export type { crossChainNameServiceReceiverSol };
export type { CCIPLocalSimulator } from "./CCIPLocalSimulator";
export type { CrossChainNameServiceLookup } from "./CrossChainNameServiceLookup";
export type { CrossChainNameServiceRegister } from "./CrossChainNameServiceRegister";
export type { ICrossChainNameServiceLookup } from "./ICrossChainNameServiceLookup";
export type { MockRouter } from "./MockRouter";
