/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CrossChainNameServiceReceiver } from "./CrossChainNameServiceReceiver";
export type { CrossChainNameServiceRegister } from "./CrossChainNameServiceRegister";
