/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CrossChainNameServiceReceiver__factory } from "./CrossChainNameServiceReceiver__factory";
export { CrossChainNameServiceRegister__factory } from "./CrossChainNameServiceRegister__factory";
